# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/adminWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 496)
        self.statusTextEdit = QtWidgets.QTextBrowser(Form)
        self.statusTextEdit.setGeometry(QtCore.QRect(10, 10, 491, 481))
        self.statusTextEdit.setObjectName("statusTextEdit")
        self.usersList = QtWidgets.QListWidget(Form)
        self.usersList.setGeometry(QtCore.QRect(510, 10, 231, 481))
        self.usersList.setObjectName("usersList")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
