# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/groupFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(481, 405)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fileTable.setFont(font)
        self.fileTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.fileTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fileTable.setShowGrid(True)
        self.fileTable.setGridStyle(QtCore.Qt.SolidLine)
        self.fileTable.setWordWrap(True)
        self.fileTable.setCornerButtonEnabled(True)
        self.fileTable.setObjectName("fileTable")
        self.fileTable.setColumnCount(5)
        self.fileTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fileTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileTable.setHorizontalHeaderItem(4, item)
        self.fileTable.horizontalHeader().setVisible(True)
        self.fileTable.verticalHeader().setVisible(False)
        self.fileTable.verticalHeader().setCascadingSectionResizes(False)
        self.fileTable.verticalHeader().setHighlightSections(True)
        self.fileTable.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.fileTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.upLoadFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.upLoadFileButton.setMinimumSize(QtCore.QSize(120, 0))
        self.upLoadFileButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.upLoadFileButton.setObjectName("upLoadFileButton")
        self.horizontalLayout.addWidget(self.upLoadFileButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.downloadButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.downloadButton.setMinimumSize(QtCore.QSize(120, 0))
        self.downloadButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fileTable.setSortingEnabled(False)
        item = self.fileTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "  "))
        item = self.fileTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "文件名"))
        item = self.fileTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "上传者"))
        item = self.fileTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "上传时间"))
        item = self.fileTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "下载次数"))
        self.upLoadFileButton.setText(_translate("Form", "上传文件"))
        self.downloadButton.setText(_translate("Form", "批量下载"))
