# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(260, 702)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nicknameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nicknameLabel.setObjectName("nicknameLabel")
        self.verticalLayout_2.addWidget(self.nicknameLabel)
        self.signatureLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.signatureLabel.setObjectName("signatureLabel")
        self.verticalLayout_2.addWidget(self.signatureLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.infoButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoButton.sizePolicy().hasHeightForWidth())
        self.infoButton.setSizePolicy(sizePolicy)
        self.infoButton.setMinimumSize(QtCore.QSize(0, 0))
        self.infoButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.infoButton.setObjectName("infoButton")
        self.horizontalLayout.addWidget(self.infoButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.FriendsList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.FriendsList.setObjectName("FriendsList")
        self.verticalLayout.addWidget(self.FriendsList)
        self.addFriendBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addFriendBtn.setObjectName("addFriendBtn")
        self.verticalLayout.addWidget(self.addFriendBtn)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.nicknameLabel.setText(_translate("Form", "TextLabel"))
        self.signatureLabel.setText(_translate("Form", "TextLabel"))
        self.infoButton.setText(_translate("Form", "个人资料"))
        self.addFriendBtn.setText(_translate("Form", "添加好友"))
